from enum import IntFlag


class HyundaiSafetyFlagsIQ:
  DEFAULT = 0
  ESCC = 16
  MAIN_BTN_LONG_TOGGLE = 32
  HAS_LDA_BUTTON = 64
  NON_SCC = 128


class HyundaiFlagsIQ(IntFlag):
  ENHANCED_SCC = 1
  HAS_LFA_BUTTON = 2
  MAIN_BTN_LONG_TOGGLE = 2 ** 2
  ENABLE_RADAR_TRACKS_DEPRECATED = 2 ** 3
  LONG_TUNING_DYNAMIC = 2 ** 4
  LONG_TUNING_PREDICTIVE = 2 ** 5
  NON_SCC = 2 ** 6
  NON_SCC_RADAR_FCA = 2 ** 7
  NON_SCC_NO_FCA = 2 ** 8
  SPEED_LIMIT_AVAILABLE = 2 ** 9
  HAS_LKAS12 = 2 ** 10


