#pragma once

#include <string>
#include <unordered_map>

#include "cereal/gen/cpp/log.capnp.h"

inline static std::unordered_map<std::string, ParamKeyAttributes> keys = {
    {"AccessToken", {CLEAR_ON_MANAGER_START | DONT_LOG, STRING}},
    {"AdbEnabled", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"AlwaysOnDM", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"ApiCache_Device", {PERSISTENT, STRING}},
    {"ApiCache_FirehoseStats", {PERSISTENT, JSON}},
    {"AssistNowToken", {PERSISTENT, STRING}},
    {"AthenadPid", {PERSISTENT, INT}},
    {"AthenadUploadQueue", {PERSISTENT, JSON}},
    {"AthenadRecentlyViewedRoutes", {PERSISTENT, STRING}},
    {"BackupManagerK3_CreateBackup", {CLEAR_ON_MANAGER_START, BOOL}},
    {"BackupManagerK3_RestoreVersion", {CLEAR_ON_MANAGER_START, STRING}},
    {"BootCount", {PERSISTENT, INT}},
    {"CalibrationParams", {PERSISTENT, BYTES}},
    {"CameraDebugExpGain", {CLEAR_ON_MANAGER_START, STRING}},
    {"CameraDebugExpTime", {CLEAR_ON_MANAGER_START, STRING}},
    {"CarBatteryCapacity", {PERSISTENT, INT}},
    {"CarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"CarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"CarParamsPersistent", {PERSISTENT, BYTES}},
    {"CarParamsPrevRoute", {PERSISTENT, BYTES}},
    {"CompletedTrainingVersion", {PERSISTENT, STRING, "0"}},
    {"ControlsReady", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"CurrentBootlog", {PERSISTENT, STRING}},
    {"CurrentRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"DisableLogging", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"DisablePowerDown", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"DisableUpdates", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"UpdaterInstallMode", {PERSISTENT | KONN3KT_BACKUP, STRING, "download_and_install"}},
    {"DisengageOnAccelerator", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"DongleId", {PERSISTENT, STRING}},
    {"DoReboot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DevicePowerState", {CLEAR_ON_MANAGER_START, STRING}},
    {"DoShutdown", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DoUninstall", {CLEAR_ON_MANAGER_START, BOOL}},
    {"DriverTooDistracted", {CLEAR_ON_MANAGER_START | CLEAR_ON_IGNITION_ON, BOOL}},
    {"AlphaLongitudinalEnabled", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"ExperimentalMode", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"ExperimentalModeConfirmed", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"FastSleep", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"FirmwareQueryDone", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ForcePowerDown", {PERSISTENT, BOOL}},
    {"GitAuthBlob", {PERSISTENT, BYTES}},
    {"GitBranch", {PERSISTENT, STRING}},
    {"GitCommit", {PERSISTENT, STRING}},
    {"GitCommitDate", {PERSISTENT, STRING}},
    {"GitDiff", {PERSISTENT, STRING}},
    {"GithubSshKeys", {PERSISTENT | KONN3KT_BACKUP, STRING}},
    {"GithubUsername", {PERSISTENT | KONN3KT_BACKUP, STRING}},
    {"GitRemote", {PERSISTENT, STRING}},
    {"GsmApn", {PERSISTENT | KONN3KT_BACKUP, STRING}},
    {"GsmMetered", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"GsmRoaming", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"HardwareSerial", {PERSISTENT, STRING}},
    {"HasAcceptedTerms", {PERSISTENT, STRING, "0"}},
    {"HephaestusdPid", {PERSISTENT, INT}},
    {"InstallDate", {PERSISTENT, TIME}},
    {"IsDriverViewEnabled", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsEngaged", {PERSISTENT, BOOL}},
    {"IsLdwEnabled", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"IsLiveStreaming", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsMetric", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"IsOffroad", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsOnroad", {PERSISTENT, BOOL}},
    {"IsRhdDetected", {PERSISTENT, BOOL}},
    {"IsReleaseBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTakingSnapshot", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsTestedBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"JoystickDebugMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"JoystickAolRequest", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, STRING}},
    {"Konn3ktSshKeys", {PERSISTENT, STRING}},
    {"Konn3ktBleTransportEnabled", {PERSISTENT, BOOL, "1"}},
    {"LanguageSetting", {PERSISTENT | KONN3KT_BACKUP, STRING, "en"}},
    {"LastAthenaPingTime", {CLEAR_ON_MANAGER_START, INT}},
    {"LastGPSPosition", {PERSISTENT, STRING}},
    {"LastManagerExitReason", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastOffroadStatusPacket", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, JSON}},
    {"LastAgnosPowerMonitorShutdown", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastPowerDropDetected", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateException", {CLEAR_ON_MANAGER_START, STRING}},
    {"LastUpdateRouteCount", {PERSISTENT, INT, "0"}},
    {"LastUpdateTime", {PERSISTENT, TIME}},
    {"LastUpdateUptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"LiveDelay", {PERSISTENT | KONN3KT_BACKUP, BYTES}},
    {"LiveParameters", {PERSISTENT, JSON}},
    {"LiveParametersV2", {PERSISTENT, BYTES}},
    {"LivestreamEncoderBitrate", {CLEAR_ON_MANAGER_START | DONT_LOG, INT}},
    {"LivestreamRequestKeyframe", {CLEAR_ON_MANAGER_START | DONT_LOG, BOOL}},
    {"LiveTorqueParameters", {PERSISTENT | DONT_LOG, BYTES}},
    {"LocationFilterInitialState", {PERSISTENT, BYTES}},
    {"LateralManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalManeuverMode", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"LongitudinalPersonality", {PERSISTENT | KONN3KT_BACKUP, INT, std::to_string(static_cast<int>(cereal::LongitudinalPersonality::STANDARD))}},
    {"NetworkMetered", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"ObdMultiplexingChanged", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"ObdMultiplexingEnabled", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"Offroad_CarUnrecognized", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_ConnectivityNeeded", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ConnectivityNeededPrompt", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_ExcessiveActuation", {PERSISTENT, JSON}},
    {"Offroad_IsTakingSnapshot", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_StorageMissing", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NeosUpdate", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_NoFirmware", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_Recalibration", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_TemperatureTooHigh", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UnregisteredHardware", {CLEAR_ON_MANAGER_START, JSON}},
    {"Offroad_UpdateFailed", {CLEAR_ON_MANAGER_START, JSON}},
    {"OnroadCycleRequested", {CLEAR_ON_MANAGER_START, BOOL}},
    {"OpenpilotEnabledToggle", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"PandaHeartbeatLost", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSomResetTriggered", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"PandaSignatures", {CLEAR_ON_MANAGER_START, BYTES}},
    {"PrimeType", {PERSISTENT, INT}},
    {"RecordAudio", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"RecordAudioFeedback", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"DashcamEnabled", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"RecordFront", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"RecordFrontLock", {PERSISTENT, BOOL}},  // for the internal fleet
    {"SecOCKey", {PERSISTENT | DONT_LOG | KONN3KT_BACKUP, STRING}},
    {"ShowDebugInfo", {PERSISTENT, BOOL}},
    {"RouteCount", {PERSISTENT, INT, "0"}},
    {"SnoozeUpdate", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, BOOL}},
    {"SshEnabled", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"TermsVersion", {PERSISTENT, STRING}},
    {"TorqueBar", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"TrainingVersion", {PERSISTENT, STRING}},
    {"UbloxAvailable", {PERSISTENT, BOOL}},
    {"UsbStorageEnabled", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"UpdateAvailable", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BOOL}},
    {"UpdateFailedCount", {CLEAR_ON_MANAGER_START, INT}},
    {"UpdaterAvailableBranches", {PERSISTENT, STRING}},
    {"UpdaterCurrentDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterCurrentReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterFetchAvailable", {CLEAR_ON_MANAGER_START, BOOL}},
    {"UpdaterNewDescription", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterNewReleaseNotes", {CLEAR_ON_MANAGER_START, BYTES}},
    {"UpdaterState", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterTargetBranch", {CLEAR_ON_MANAGER_START, STRING}},
    {"UpdaterLastFetchTime", {PERSISTENT, TIME}},
    {"UptimeOffroad", {PERSISTENT, FLOAT, "0.0"}},
    {"UptimeOnroad", {PERSISTENT, FLOAT, "0.0"}},
    {"Version", {PERSISTENT, STRING}},

    // --- iqpilot params --- //
    {"ApiCache_DriveStats", {PERSISTENT, JSON}},
    {"AutoLaneChangeBsmDelay", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"AutoLaneChangeTimer", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"NavExitLaneChange", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"IQBlinkerMinLateralSpeed", {PERSISTENT | KONN3KT_BACKUP, INT, "20"}},  // MPH or km/h
    {"IQBlinkerPauseLateral", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"Brightness", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"CarList", {PERSISTENT, JSON}},
    {"IQCarParams", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, BYTES}},
    {"IQCarParamsCache", {CLEAR_ON_MANAGER_START, BYTES}},
    {"IQCarParamsPersistent", {PERSISTENT, BYTES}},
    {"IQCarParamsPersistentV2", {PERSISTENT, BYTES}},
    {"CarPlatformBundle", {PERSISTENT | KONN3KT_BACKUP, JSON}},
    {"ChevronInfo", {PERSISTENT | KONN3KT_BACKUP, INT, "4"}},
    {"DeviceBootMode", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"IQDevUIInfo", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"EnableEsimProvisioning", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"GreenLightAlert", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"InteractivityTimeout", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"IsDevelopmentBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"IsReleaseIqBranch", {CLEAR_ON_MANAGER_START, BOOL}},
    {"LastGPSPositionIQLoc", {PERSISTENT, STRING}},
    {"LeadDepartAlert", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"LongIncrementsEnabled", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"LongIncrementTapStep", {PERSISTENT | KONN3KT_BACKUP, INT, "1"}},
    {"LongIncrementHoldStep", {PERSISTENT | KONN3KT_BACKUP, INT, "5"}},
    {"IQE2ESetSpeedMode", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"IQE2ESetSpeedUseCurrent", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"IQE2ESetSpeedMph", {PERSISTENT | KONN3KT_BACKUP, INT, "65"}},
    {"MaxTimeOffroad", {PERSISTENT | KONN3KT_BACKUP, INT, "1800"}},
    {"NightMode", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"newLeadMpc", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"ModelRunnerTypeCache", {CLEAR_ON_ONROAD_TRANSITION, INT}},
    {"ForceOnroadUntil", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, INT, "0"}},
    {"OffroadMode", {CLEAR_ON_MANAGER_START, BOOL}},
    {"Offroad_TiciSupport", {CLEAR_ON_MANAGER_START, JSON}},
    {"OnroadScreenOffBrightness", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"OnroadScreenOffTimer", {PERSISTENT | KONN3KT_BACKUP, INT, "15"}},
    {"OnScreenNavigation", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"OnlineOSMaps", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"OfflineOSMaps", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"OSMapsStyleMode", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"OSMapsHeadingUp", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"OfflineTilesBaseUrl", {PERSISTENT, STRING}},
    {"OnroadUploads", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"IQAlertSilence", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"RainbowMode", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"RocketFuel", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"ShowTurnSignals", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"StandstillTimer", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    // AOL (Always On Lateral) params
    {"AolEnabled", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"AolMainCruiseAllowed", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"AolSteeringMode", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"AolUnifiedEngagementMode", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},

    // Model Manager params
    {"ModelManager_ActiveBundle", {PERSISTENT, JSON}},
    {"ModelManager_ClearCache", {CLEAR_ON_MANAGER_START, BOOL}},
    {"ModelManager_DownloadIndex", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, INT, "-1"}},
    {"ModelManager_Favs", {PERSISTENT | KONN3KT_BACKUP, STRING}},
    {"ModelManager_LastSyncTime", {CLEAR_ON_MANAGER_START | CLEAR_ON_OFFROAD_TRANSITION, INT, "0"}},
    {"ModelManager_ModelsCache", {PERSISTENT | KONN3KT_BACKUP, JSON}},

    // Neural Network Feed Forward
    {"NeuralNetworkFeedForward", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},

    // Backup Manager params
    {"BackupManager_CreateBackup", {PERSISTENT, BOOL}},
    {"BackupManager_RestoreVersion", {PERSISTENT, STRING}},

    // iqpilot car specific params
    {"HyundaiLongitudinalTuning", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"SubaruStopAndGo", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"SubaruStopAndGoManualParkingBrake", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"TeslaCoopSteering", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"ToyotaEnforceStockLongitudinal", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"VwPqEpsPatched", {PERSISTENT, BOOL}},
    {"ToyotaSnGHack", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"pqhca5or7Toggle", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"iqMqbAccResume", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"iqMqbSteeringLockout", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"AllowLateralWhenLongUnavailable", {PERSISTENT | KONN3KT_BACKUP, BOOL}},

    {"IQDynamicMode", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"IQDynamicBlendStockRadar", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"IQDynamicConditionalCurves", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"IQDynamicConditionalSlowerLead", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"IQDynamicConditionalStoppedLead", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"IQDynamicConditionalModelStops", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"IQDynamicConditionalSLCFallback", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"IQDynamicConditionalSpeed", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "18.0"}},
    {"IQDynamicConditionalLeadSpeed", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "24.0"}},
    {"IQDynamicModelStopTime", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "3.0"}},
    {"IQDynamicMinimumForceStopLength", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "0.0"}},
    {"IQForceStops", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"IQCustomStopDistance", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},  // meters, -2..2; negative = stop closer, positive = stop further back; independent of IQForceStops
    {"BlindSpot", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"IQExpandedStatus", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"HomePanelWidget", {PERSISTENT, STRING, "changelog"}},

    // iqpilot model params
    {"CameraOffset", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "0.0"}},
    {"LagdToggle", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"LagdToggleDelay", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "0.2"}},
    {"LagdValueCache", {PERSISTENT, FLOAT, "0.2"}},
    {"LaneChangeBsd", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},          // -1 ignore BSD, 0 default, 1 block lane change on BSD
    {"LaneChangeContinuous", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},  // 0 one-shot per blinker, 1 chain on held blinker (torque-gated)
    {"LaneChangeDelay", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "0.0"}},    // tenths of a second; scaled by 0.1 in desire_helper
    {"LaneChangeNeedTorque", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},   // <0 disable blinker LC, 0 default, >0 require torque
    {"IQLaneTurnDesire", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"IQLaneTurnValue", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "19.0"}},
    {"PlanplusControl", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "1.0"}},
    {"LatSmoothSec", {PERSISTENT, INT, "13"}},
    {"ModelSmoothingEnabled", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"ModelLatSmoothSec", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},

    // IQ.Pilot Parameters:
    {"ShowBSMIndicators", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"ShowSteeringArc", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"ShowRoadName", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"ShowRealTimeAcceleration", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"ForceSmallUI", {PERSISTENT, BOOL, "0"}},
    {"DeveloperUI", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"OBrightness", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"OBrightnessManual", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"OBrightnessDelay", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"MapAdvisorySpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, FLOAT}},
    {"MapdVersion", {PERSISTENT, STRING}},
    {"MapdSettings", {PERSISTENT, JSON}},  // pfeiferj/mapd v2 persistent settings (read/written by the mapd binary)
    {"MapSpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, FLOAT, "0.0"}},
    {"NextMapSpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"Offroad_OSMUpdateRequired", {CLEAR_ON_MANAGER_START, JSON}},
    {"OsmDbUpdatesCheck", {CLEAR_ON_MANAGER_START, BOOL}},  // mapd database update happens with device ON, reset on boot
    {"OSMDownloadBounds", {PERSISTENT, STRING}},
    {"OsmDownloadedDate", {PERSISTENT, STRING, "0.0"}},
    {"OSMDownloadLocations", {PERSISTENT, JSON}},
    {"AthenaNavigationRoute", {CLEAR_ON_MANAGER_START, JSON}},
    {"NavigationActive", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"NavigationDestination", {CLEAR_ON_MANAGER_START, JSON}},
    {"NavigationEnabled", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"NavigationDebugFlags", {PERSISTENT | KONN3KT_BACKUP, JSON}},
    {"NavigationManeuvers", {CLEAR_ON_MANAGER_START, JSON}},
    {"NavigationPreferences", {PERSISTENT | KONN3KT_BACKUP, JSON}},
    {"NavigationRenderRoute", {CLEAR_ON_MANAGER_START | CLEAR_ON_ONROAD_TRANSITION, JSON}},
    {"NavigationRecalculateRoutes", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"NavigationRouteAlternatives", {CLEAR_ON_MANAGER_START, JSON}},
    {"NavigationRouteSelection", {CLEAR_ON_MANAGER_START, JSON}},
    {"ScreenRecording", {CLEAR_ON_MANAGER_START, BOOL, "0"}},
    {"OSMDownloadProgress", {CLEAR_ON_MANAGER_START, JSON}},
    {"OfflineTilesDownloadProgress", {CLEAR_ON_MANAGER_START, JSON}},
    {"OfflineTilesDownloadRequest", {PERSISTENT, JSON}},
    {"OsmLocal", {PERSISTENT, BOOL}},
    {"OsmLocationName", {PERSISTENT, STRING}},
    {"OsmLocationTitle", {PERSISTENT, STRING}},
    {"OsmLocationUrl", {PERSISTENT, STRING}},
    {"OsmStateName", {PERSISTENT, STRING, "All"}},
    {"OsmStateTitle", {PERSISTENT, STRING}},
    {"OsmStateNames", {PERSISTENT, JSON}},
    {"OsmWayTest", {PERSISTENT, STRING}},
    {"RoadName", {CLEAR_ON_ONROAD_TRANSITION, STRING}},
    {"RoadNameToggle", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"IQSpeedAssistMode", {PERSISTENT | KONN3KT_BACKUP, INT, "1"}},
    {"IQSpeedAssistOffsetType", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"IQSpeedAssistPolicy", {PERSISTENT | KONN3KT_BACKUP, INT, "3"}},
    {"IQSpeedAssistValueOffset", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"SpeedLimitController", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"ConstructionZoneAssist", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"VisionVehicleTracks", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"AmbientTrackDots", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"ConstructionZoneSpeed", {PERSISTENT | KONN3KT_BACKUP, INT, "60"}},
    {"ShowSpeedLimits", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"SLCPolicy", {PERSISTENT | KONN3KT_BACKUP, INT, "1"}},
    {"SLCAutoConfirm", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"SLCSetSpeedToLimit", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"speed_limit_offset1", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "0"}},
    {"speed_limit_offset2", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "0"}},
    {"speed_limit_offset3", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "0"}},
    {"speed_limit_offset4", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "0"}},
    {"speed_limit_offset5", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "0"}},
    {"speed_limit_offset6", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "0"}},
    {"speed_limit_offset7", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "0"}},
    {"SpeedLimitConfirmationHigher", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"SpeedLimitConfirmationLower", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"MapSpeedLookaheadHigher", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "5.0"}},
    {"MapSpeedLookaheadLower", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "5.0"}},
    {"SLCFallbackExperimentalMode", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"SLCFallbackSetSpeed", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"SLCFallbackPreviousSpeedLimit", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"SLCOverrideMethod", {PERSISTENT | KONN3KT_BACKUP, INT, "0"}},
    {"SLCOnlineFiller", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"SLCDataCollection", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"MapBoxRequests", {PERSISTENT, JSON}},
    {"OverpassRequests", {PERSISTENT, JSON}},
    {"SpeedLimits", {PERSISTENT, JSON}},
    {"SpeedLimitsFiltered", {PERSISTENT, JSON}},
    {"PreviousSpeedLimit", {PERSISTENT, FLOAT, "0"}},
    {"UpdateSpeedLimits", {CLEAR_ON_IGNITION_ON}},
    {"UpdateSpeedLimitsStatus", {CLEAR_ON_IGNITION_ON, STRING}},
    {"SLCMapboxSpeedLimit", {CLEAR_ON_ONROAD_TRANSITION, FLOAT, "0"}},
    {"NavigateOnIQPilot", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"NavOnlineTargets", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"NavOfflineFallback", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"NavPreferOfflineSources", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"OfflineRoutingEnabled", {PERSISTENT | KONN3KT_BACKUP, BOOL, "1"}},
    {"OfflineRoutingOnly", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"OfflineRoutingHost", {PERSISTENT | KONN3KT_BACKUP, STRING, "http://127.0.0.1:8002"}},
    {"pqhca5or7Toggle", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"AllowLateralWhenLongUnavailable", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"EnableCurvatureController", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"EnableSpeedLimitControl", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"MapCurveSpeedController", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"VisionCurveSpeedController", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"SpeedCameraAlerts", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"RedLightCameraAlerts", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"FlockCameraAlerts", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"SpeedCameraSlowdown", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"SpeedCameraSafetyFactor", {PERSISTENT | KONN3KT_BACKUP, FLOAT, "1.0"}},
    {"NavCamerasData", {PERSISTENT, JSON}},
    {"EnableLongComfortMode", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"EnableSpeedLimitPredicative", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"EnableSLPredReactToSL", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"EnableSLPredReactToCurves", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"ForceRHDForBSM", {PERSISTENT | KONN3KT_BACKUP, BOOL, "0"}},
    {"NavDestination", {PERSISTENT, STRING}},
    {"eBrakeActive", {CLEAR_ON_MANAGER_START | KONN3KT_BACKUP, BOOL, "0"}},
    {"Konn3ktAllowOffroadExternalCanTx", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"MapboxToken", {PERSISTENT | KONN3KT_BACKUP, STRING}},
    {"MapboxTokenQRCode", {PERSISTENT | KONN3KT_BACKUP, JSON}},
    {"TomTomToken", {PERSISTENT | KONN3KT_BACKUP, STRING}},
    {"UIAccentColor", {PERSISTENT | KONN3KT_BACKUP, STRING, "#00FFF5"}},
    {"AngleLateralControl", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
    {"ALCTorqueBlend", {PERSISTENT | KONN3KT_BACKUP, BOOL}},
};
